server:
  port: 8085
  error:
    include-exception: true
    include-message: always
#
#logging:
#  config: src/main/resources/logback.xml
#  level:
#    com.hl.magic: Info

spring:
  rabbitmq:
    host: localhost
    port: 5672
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qiniu
    username: root
    password: tianling
    druid:
      #初始连接池值
      initial-size: 10
      #最大连接数
      max-active: 100
      #最小连接数
      min-idle: 10
      #连接等待时间
      max-wait: 60000
      #
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #配置StatViewServlet监控页面
      stat-view-servlet:
        #开启
        enabled: true
        #访问监控路径的地址
        url-pattern: /druid/*
        #不允许清空，重新统计
        reset-enable: false
        #登录用户名
        login-username: admin
        #登录密码
        login-password: admin
        #允许访问地址
        allow: localhost
      ########## 配置WebStatFilter，用于采集web关联监控的数据 #########
      web-stat-filter:
        #启动statFilter
        enabled: true
        #排除的url
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        #开启session统计
        session-stat-enable: true
        #session的最大个数，默认为100
        session-stat-max-count: 1000
        #过滤的url
        url-pattern: /*
      filter:
        stat:
          #开启慢sql统计
          log-slow-sql: true
          #慢sql的时间
          slow-sql-millis: 2000
          merge-sql: true
          #开启druid datasource监控
          enabled: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 0
    # 公网 r-bp1z46bf7a5feu5gozpd.redis.rds.aliyuncs.com
    # 内网 r-bp1z46bf7a5feu5goz.redis.rds.aliyuncs.com
    host: localhost
    port: 6379
    connect-timeout: 6000ms
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.example.tianling.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# minio 文件存储配置信息
minio:
  endpoint: http://120.26.76.250:9000
  accesskey: admin
  secretKey: tianling

qiniu:
  access-key: 9QfKMtzI2fBWBmIX0JBzqwHaz5noF8-WkOBK_I0j
  secret-key: QynvFpejg2y7YvBi1b6thXW8eXTZhsLmhkK6JoBf
  bucket-name: tianling666
  bucket-domain: s3g45msqv.hn-bkt.clouddn.com